### ISSUE TITLE
Crashing on Mod Loading Phase 2     net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pony Magic (ponymagic)

### ISSUE THREAD

**Issue by Guardduck987** [PonyMagic/PonyMagic#7]
The game Crashes without any other mods on forge 2855 and 2854 with the attached Crashreport
[crash-2021-12-11_13.30.35-client.txt](https://github.com/PonyMagic/PonyMagic/files/7696978/crash-2021-12-11_13.30.35-client.txt)

**Comment by RandomPony** [comment]
You need to have [Potion Core 1.8](https://www.curseforge.com/minecraft/mc-mods/potion-core/files/2736248) installed to run this mod

**Comment by eliskvitka** [comment]
Install Potion Core
